main: com.jurassiklizard.nethernerf.NetherNerf
version: 1.0
name: NetherNerf
author: JurassikLizard
api-version: 1.16
commands:
  nnaddworld:
    usage: /<command> <world_name>
    description: Add nether world to list of manhunt worlds.
    aliases:
      nnaw
  nnremoveworld:
    usage: /<command> <world_name>
    description: Remove nether world to list of manhunt worlds.
    aliases:
      nnrw
  nnaddplayer:
    usage: /<command> <player_name>
    description: Add player to list of speedrunners.
    aliases:
      nnap
  nnremoveplayer:
    usage: /<command> <player_name>
    description: Remove player to list of speedrunners.
    aliases:
      nnrp